"""Added TestEquipment model

Revision ID: 24db33c456d7
Revises: bbfd54617f88
Create Date: 2021-08-29 08:55:39.578959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24db33c456d7'
down_revision = 'bbfd54617f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('manufacturer', sa.String(length=24), nullable=True),
    sa.Column('model_num', sa.String(length=24), nullable=True),
    sa.Column('serial_num', sa.Integer(), nullable=True),
    sa.Column('calibration_due_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_equipment')
    # ### end Alembic commands ###
