"""empty message

Revision ID: 6c0333134a90
Revises: 7c5af9323d51
Create Date: 2021-08-21 17:25:21.524034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0333134a90'
down_revision = '7c5af9323d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('channel', sa.Column('injection_units', sa.String(length=16), nullable=True))
    # op.drop_column('channel', 'test_units')    
    # ### end Alembic commands ###
    #
    # Manual changes
    with op.batch_alter_table('channel') as batch_op:
        batch_op.alter_column('test_units', new_column_name='injection_units')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('channel', sa.Column('test_units', sa.VARCHAR(length=16), nullable=True))
    # op.drop_column('channel', 'injection_units')
    # ### end Alembic commands ###
    #
    # Manual changes
    with op.batch_alter_table('channel') as batch_op:
        batch_op.alter_column('injection_units', new_column_name='test_units')
