"""Added ForeignKey to company_category

Revision ID: b766e7df7b55
Revises: fcd72ac00f6d
Create Date: 2021-09-09 23:33:00.162257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b766e7df7b55'
down_revision = 'fcd72ac00f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'approval_record', 'company', ['company_category'], ['category'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'approval_record', type_='foreignkey')
    # ### end Alembic commands ###
