"""Moved notes to channel and added interface

Revision ID: b7961a27f4cd
Revises: d695e18ea510
Create Date: 2021-08-31 23:35:12.528269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7961a27f4cd'
down_revision = 'd695e18ea510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('interface', sa.String(length=32), nullable=True))
    op.add_column('channel', sa.Column('notes', sa.String(length=128), nullable=True))
    op.drop_column('test_point', 'notes')
    # ### end Alembic commands ###

    # Manual commands for previous column alter
    with op.batch_alter_table('test_point') as batch_op:
        batch_op.drop_column('notes')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_point', sa.Column('notes', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('channel', 'notes')
    op.drop_column('channel', 'interface')
    # ### end Alembic commands ###

    # Manual commands for previous column alter
    with op.batch_alter_table('test_point') as batch_op:
        batch_op.add_column('test_point', sa.Column('notes', sa.String(length=128), nullable=True))
