"""Added status fields to each Model

Revision ID: bbfd54617f88
Revises: 5f9f7f9e97d6
Create Date: 2021-08-25 19:49:03.508124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfd54617f88'
down_revision = '5f9f7f9e97d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('group', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('job', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('project', sa.Column('status', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'status')
    op.drop_column('job', 'status')
    op.drop_column('group', 'status')
    op.drop_column('channel', 'status')
    # ### end Alembic commands ###
