"""Added first and last names to user

Revision ID: c26a3b11787e
Revises: c8fa34a8d6ba
Create Date: 2021-09-09 17:08:38.283729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26a3b11787e'
down_revision = 'c8fa34a8d6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=48), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
