"""Added test equipment calibration records

Revision ID: cb9128c63f65
Revises: d1306cd646c4
Create Date: 2021-09-02 18:55:10.265803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9128c63f65'
down_revision = 'd1306cd646c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''op.create_table('calibration_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calibration_date', sa.DateTime(), nullable=True),
    sa.Column('calibration_due_date', sa.DateTime(), nullable=True),
    sa.Column('test_equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_equipment_id'], ['test_equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channel_equipment', sa.Column('test_equipment_calibration_due_date', sa.DateTime(), nullable=True))
    op.add_column('channel_equipment', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('test_equipment', 'calibration_due_date') '''
    # ### end Alembic commands ###

    with op.batch_alter_table('test_equipment') as batch_op:
        batch_op.drop_column('calibration_due_date')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_equipment', sa.Column('calibration_due_date', sa.DATETIME(), nullable=True))
    op.drop_column('channel_equipment', 'timestamp')
    op.drop_column('channel_equipment', 'test_equipment_calibration_due_date')
    op.drop_table('calibration_record')
    # ### end Alembic commands ###
