"""Added test_equipment_type_id to the ChannelEquipmentRecord

Revision ID: cc9e10bbc611
Revises: 2b023b98f6c7
Create Date: 2021-09-05 22:39:56.160482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9e10bbc611'
down_revision = '2b023b98f6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_equipment_record', sa.Column('test_equipment_type_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_equipment_record', 'test_equipment_type_id')
    # ### end Alembic commands ###
