"""Changed TestEquipmentType to a ForeignKey

Revision ID: deed52f7b801
Revises: cc9e10bbc611
Create Date: 2021-09-05 22:44:16.742124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deed52f7b801'
down_revision = 'cc9e10bbc611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'channel_equipment_record', 'test_equipment_type', ['test_equipment_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel_equipment_record', type_='foreignkey')
    # ### end Alembic commands ###
